version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9317:9317
    depends_on: 
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123456
      MYSQL_DATABASE: cloud_auto
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/cloud_auto.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    command: --default-authentication-plugin=mysql_native_password


  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
