version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9317:9317
    depends_on: 
      mysql:
        condition: service_completed_successfully
      redis:
        condition: service_completed_successfully
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123456
      MYSQL_DATABASE: cloud_auto
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server.cloud_auto.sql:/docker-entrypoint-initdb.d/init.sql


  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

volumes:
  mysql_data:
